# Generated by Django 3.1.7 on 2021-03-30 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_category_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='take_clubs_from_category', to='sport.category'),
        ),
    ]
