# Generated by Django 3.1.7 on 2021-03-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_auto_20210330_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='schedule_number',
            field=models.IntegerField(default=0),
        ),
    ]
