# Generated by Django 3.1.7 on 2021-03-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_club_schedule_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_number', models.IntegerField(default=0)),
                ('max_player', models.IntegerField(default=2)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('address', models.CharField(max_length=250)),
                ('address_number', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('USA', 'United States of America')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='schedule_number',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_res', models.DateField()),
                ('hour_res', models.TimeField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_Reservation_from_field', to='sport.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_Reservation_from_user', to='sport.field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_field_from_club', to='sport.club'),
        ),
    ]
