# Generated by Django 3.1.7 on 2021-03-30 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_auto_20210330_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.AddField(
            model_name='field',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='take_fields_from_category', to='sport.category'),
        ),
        migrations.AlterField(
            model_name='field',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='schedule_number',
            field=models.IntegerField(default=7),
        ),
    ]
