# Generated by Django 3.1.7 on 2021-03-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_auto_20210330_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
