# Generated by Django 3.1.7 on 2021-03-30 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_field_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_Reservation_from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
