# Generated by Django 3.1.7 on 2021-04-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0013_remove_field_max_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hour_book',
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule_time_field',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_Schedule_from_field', to='sport.field')),
            ],
        ),
    ]
