# Generated by Django 3.1.7 on 2021-04-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0015_auto_20210403_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='schedule_number',
        ),
    ]
